spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///test
    username: root
    password: SPF940805.
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  thymeleaf:
    prefix: /WEB-INF/view/
    suffix: .html
    cache: false
  devtools:
    restart:
      additional-paths: src\\main\\java\\com\\SpringBoot\\ibats
      exclude: /WEB-INF/view
mybatis:
  mapperLocations: classpath:mappers/*.xml
  typeAliasesPackage: com.SpringBoot.ibats.model
